### ISSUE TITLE
SVG class names not showing upon inspection

### ISSUE THREAD

**Issue by Inwerpsel** [Inwerpsel/use-theme-editor#24]
While creating the code that extracts classes for an element, I made the apparently unreasonable assumption that this is just a string.

However, for SVGs it's a [SVGAnimatedString](https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedString), which is an object. I previously checked for its type as a quick fix.

Currently these classes are only used to format the label of the groups:

https://github.com/Inwerpsel/use-theme-editor/blob/2928d3d2cdd4619a073893ba3e8fe4bb3c7ee369/src/functions/groupVars.js#L9

**Comment by The-Alan-Turing** [comment]
Can you please guide me to the exact place in the code where we extract classes for an element?

**Comment by Inwerpsel** [comment]
Sure, I added it to the description.

**Comment by Inwerpsel** [comment]
I'm also interested to hear if there's any issues running and testing the code locally, feel free to report anything you'd come across 🙏
